# .readthedocs.yaml
# Read the Docs configuration file

# .readthedocs.yaml
version: 2

python:
  version: 3.6  # Use a major.minor version format

sphinx:
  configuration: docs/conf.py

build:
  image: latest  # Ensure this is the correct build setting
